/*
 * File: app/view/DetailPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Shine.view.DetailPanel', {
    extend: 'Ext.Container',

    config: {
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                height: 100,
                id: 'weather',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'container',
                        data: {
                            name: 'Brig',
                            arrivalTime: '15:04',
                            departureTime: '13:32',
                            sunLevel: 1,
                            temperature: 15,
                            forecastTime: '15.00',
                            forecastSunLevel: 2,
                            forecastTemperature: 17
                        },
                        id: 'weatherNow',
                        padding: 10,
                        tpl: [
                            '<div class="stationDetail sunLevel{sunLevel}">',
                            '    <p class="time">now</p>',
                            '    <p class="temperature">{temperature}&deg;</p>',
                            '</div>'
                        ]
                    },
                    {
                        xtype: 'container',
                        data: {
                            name: 'Brig',
                            arrivalTime: '15:04',
                            departureTime: '13:32',
                            sunLevel: 1,
                            temperature: 15,
                            forecastTime: '15.00',
                            forecastSunLevel: 2,
                            forecastTemperature: 17
                        },
                        id: 'weatherForecast',
                        padding: 10,
                        tpl: [
                            '<div class="stationDetail sunLevel{forecastSunLevel}">',
                            '    <p class="time">{forecastTime}</p>',
                            '    <p class="temperature">{forecastTemperature}&deg;</p>',
                            '</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                data: {
                    name: 'Brig',
                    arrivalTime: '15:04',
                    departureTime: '13:32',
                    sunLevel: 1,
                    temperature: 15,
                    forecastTime: '15.00',
                    forecastSunLevel: 2,
                    forecastTemperature: 17
                },
                height: 100,
                id: 'connection',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'container',
                        id: 'connectionDeparture',
                        padding: 10,
                        tpl: [
                            '    <div class="departure">',
                            '        <p class="departureStation">Bern</p>',
                            '        <p class="departureTime">{departureTime}</p>',
                            '    </div>'
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'connectionArrival',
                        padding: 10,
                        tpl: [
                            '    <div class="arrival">',
                            '        <p class="arrivalStation">{name}</p>',
                            '        <p class="arrivalTime">{arrivalTime}</p>',
                            '    </div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'map',
                padding: 10,
                items: [
                    {
                        xtype: 'map',
                        height: 200,
                        id: 'googleMap',
                        mapOptions: {
                            zoom: 8,
                            panControl: false,
                            zoomControl: false,
                            mapTypeControl: false,
                            scaleControl: false,
                            streetViewControl: false,
                            overviewMapControl: false
                        },
                        useCurrentLocation: true
                    }
                ]
            }
        ]
    }

});