/*
 * File: app/view/StationList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Shine.view.StationList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.stationlist',

    config: {
        id: 'stationList',
        store: 'Stations',
        itemTpl: [
            '<div class="stationList sunLevel{sunLevel}">',
            '    <p class="stationName">{name}</p><p class="arrivalTime">{arrivalTime}</p>',
            '</div>'
        ],
        plugins: [
            {
                type: 'pullrefresh'
            }
        ]
    }

});