/*
 * File: Shine/store/Stations.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Shine.store.Stations', {
    extend: 'Ext.data.Store',

    requires: [
        'Shine.model.Station'
    ],

    config: {
        autoLoad: true,
        model: 'Shine.model.Station',
        storeId: 'Stations',
        proxy: {
            type: 'ajax',
            url: 'stations.json',
            reader: {
                type: 'json',
                rootProperty: 'stations'
            }
        }
    }
});